definitions:
  app.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  model.Segment:
    properties:
      amountOfSegments:
        type: integer
      message:
        type: string
      segmentNum:
        type: integer
      sender:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/datalink:
    post:
      consumes:
      - application/json
      description: Кодирует данные, вносит ошибку, декодирует с исправлением, теряет
        с заданной вероятностью и отправляет в ответ
      parameters:
      - description: Пользовательский объект в формате JSON
        in: body
        name: segment
        required: true
        schema:
          $ref: '#/definitions/model.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: Успешно
          schema:
            $ref: '#/definitions/app.ResponseMessage'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/app.ResponseMessage'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/app.ResponseMessage'
      summary: Передача данных на канальном уровне
      tags:
      - DataLink
swagger: "2.0"
